a = int(input())
b = int(input())
c = int(input())
x = int(input())
y = int(input())
z = int(input())
d1 = (a // x) * (b // y) * (c // z)
d2 = (a // x) * (c // y) * (b // z)
d3 = (b // x) * (a // y) * (c // z)
d4 = (b // x) * (c // y) * (a // z)
d5 = (c // x) * (b // y) * (a // z)
d6 = (c // x) * (a // y) * (b // z)
print(max(d1, d2, d3, d4, d5, d6))
